<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'Composer\\InstalledVersions' => $vendorDir . '/composer/InstalledVersions.php',
    'franciscoblancojn\\wordpress_utils\\FWUSystemLog' => $vendorDir . '/franciscoblancojn/wordpress_utils/src/FWUSystemLog.php',
);
